### ISSUE TITLE
warning: adding embedded git repository: printer_data/config/.theme

### ISSUE THREAD

**Issue by euf0ria** [Staubgeborener/klipper-backup#111]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem

### What happened

The hidden subfolder ".theme" does not get backed up to github. 

### What did you expect to happen

All files and folders inside of getting backed up to github.

### How to reproduce

Have a hidden directory ".theme" in your config directory (this is used for customization of mailsail). Use .env file with default backupPaths. Run manual backup from klipper macro. Check the console.

### Additional information

Logs from the console after running backup macro:

```
10:06:44
Command {update_git_script_message} finished
10:06:44
Branch 'main' set up to track remote branch 'main' from 'origin'.
10:06:44
To https://github.com/euf0ria/voron-trident.git
6c63318..bc51808 main -> main
10:06:43
[main bc51808] 2024-07-29 - No new changes pushed
10:06:42
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git restore ..." to discard changes in working directory)
(commit or discard the untracked or modified content in submodules)
modified: printer_data/config/.theme (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
10:06:42
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint: git rm --cached printer_data/config/.theme
hint:
hint: See "git help submodule" for more information.
10:06:42
warning: adding embedded git repository: printer_data/config/.theme
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint: git submodule add printer_data/config/.theme
10:06:42
Skipping symbolic link: printer_data/config/timelapse.cfg
10:06:41
Skipping symbolic link: printer_data/config/mainsail.cfg
10:06:40
Already up to date.
10:06:40
From https://github.com/euf0ria/voron-trident
* branch main -> FETCH_HEAD
10:06:40
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint: git config pull.rebase false # merge (the default strategy)
hint: git config pull.rebase true # rebase
hint: git config pull.ff only # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
10:06:39
Klipper-backup is up to date
10:06:38
[1;93m●[0m Checking for installed dependencies /
[K[1;92m●[0m Checking for installed dependencies [1;92mDone![0m
10:06:38
Running Command {update_git_script_message}...:
10:06:38
update_git MESSAGE=2024-07-29
```

**Comment by Tylerjet** [comment]
Can you try deleting the config_backup folder and then try running again. The issue is that your theme is technically a git repository so it cannot be backed up properly, this is addressed on the beta/dev restore branch as instead of backing up the .theme folder we just reclone the repo when restoring and just backup the url of the them repository itself.

**Comment by Staubgeborener** [comment]
> Can you try deleting the config_backup folder and then try running again. The issue is that your theme is technically a git repository so it cannot be backed up properly, this is addressed on the beta/dev restore branch as instead of backing up the .theme folder we just reclone the repo when restoring and just backup the url of the them repository itself.

In context to this message, download the current version of klipper-backup and run `~/klipper-backup/script.sh --fix`

**Comment by euf0ria** [comment]
I have now tried updating to 1.3.1 and running the script and then tried deleting the config_backup and running the script. Still the same warning in the log and still no files in the .theme folder in the destination folder/on github.

Since the printer was not set up by myself i don´t know the whole story behind this .theme folder but I think the theme was installed from KIAUH (advanced menu > theme installer) and then it would probably be its own repository.

Since I have made modifications in the current .theme folder i would like to treat this as my own files and cut loose from the original github source. How would i go about this? Sorry if this is n00b material. Please be gentle, l´m learning this from scratch right now :).

**Comment by Tylerjet** [comment]
The most likely easiest solution would be to navigate to the theme folder and delete the .git folder located inside. (this is what tells git that it is a repo/submodule, then try the fix steps and see if the error still occurs.
